#!/usr/bin/env python3
"""
Visualizer for VTK output files generated by mcch_solver.
Extracts component fields c0, c1, c2, renders 2D slice/color maps,
and creates composite RGB phase maps with MPI slab boundary overlays.
"""

import sys
import os
import glob
import numpy as np
import matplotlib.pyplot as plt

def parse_vtk_structured_points(filepath):
    with open(filepath, 'r') as f:
        lines = f.readlines()

    nx, ny, nz = 1, 1, 1
    fields = {}
    current_scalar = None
    collecting = False
    data_tokens = []

    for line in lines:
        line_str = line.strip()
        if line_str.startswith("DIMENSIONS"):
            parts = line_str.split()
            nx, ny, nz = int(parts[1]), int(parts[2]), int(parts[3])
        elif line_str.startswith("SCALARS"):
            if current_scalar and data_tokens:
                fields[current_scalar] = np.array(data_tokens, dtype=np.float64).reshape((nz, ny, nx))
                data_tokens = []
            parts = line_str.split()
            current_scalar = parts[1]
            collecting = False
        elif line_str.startswith("LOOKUP_TABLE"):
            collecting = True
        elif collecting:
            for token in line_str.split():
                data_tokens.append(float(token))

    if current_scalar and data_tokens:
        fields[current_scalar] = np.array(data_tokens, dtype=np.float64).reshape((nz, ny, nx))

    return nx, ny, nz, fields

def visualize_solution(vtk_path, output_png=None, num_ranks=None):
    if not os.path.exists(vtk_path):
        print(f"Error: {vtk_path} does not exist.")
        return

    nx, ny, nz, fields = parse_vtk_structured_points(vtk_path)
    comp_keys = [k for k in sorted(fields.keys()) if k.startswith('c')]
    num_comps = len(comp_keys)

    if num_comps == 0:
        print("No concentration fields found in VTK.")
        return

    # Choose mid z-slice
    z_idx = nz // 2

    fig = plt.figure(figsize=(5 * (num_comps + 1), 5))

    for idx, key in enumerate(comp_keys):
        ax = fig.add_subplot(1, num_comps + 1, idx + 1)
        data_slice = fields[key][z_idx, :, :]
        im = ax.imshow(data_slice, origin='lower', cmap='viridis', extent=[0, nx, 0, ny])
        ax.set_title(f"Component ${key}$", fontsize=13, fontweight='bold')
        ax.set_xlabel('X')
        ax.set_ylabel('Y')
        plt.colorbar(im, ax=ax, fraction=0.046, pad=0.04)

        if num_ranks and num_ranks > 1:
            base = nx // num_ranks
            rem = nx % num_ranks
            x_pos = 0
            for r in range(num_ranks - 1):
                loc_nx = base + (1 if r < rem else 0)
                x_pos += loc_nx
                ax.axvline(x_pos, color='red', linestyle='--', alpha=0.7, lw=1.2)

    # Composite plot
    ax_comp = fig.add_subplot(1, num_comps + 1, num_comps + 1)
    if num_comps >= 3:
        c0 = np.clip(fields['c0'][z_idx, :, :], 0.0, 1.0)
        c1 = np.clip(fields['c1'][z_idx, :, :], 0.0, 1.0)
        c2 = np.clip(fields['c2'][z_idx, :, :], 0.0, 1.0)
        rgb = np.stack([c0, c1, c2], axis=-1)
        ax_comp.imshow(rgb, origin='lower', extent=[0, nx, 0, ny])
        ax_comp.set_title("RGB Phase Composite\n(R: $c_0$, G: $c_1$, B: $c_2$)", fontsize=12, fontweight='bold')
    else:
        # Binary phase map
        c0 = fields['c0'][z_idx, :, :]
        ax_comp.imshow(c0, origin='lower', cmap='coolwarm', extent=[0, nx, 0, ny])
        ax_comp.set_title("Binary Phase Map ($c_0$)", fontsize=12, fontweight='bold')

    ax_comp.set_xlabel('X')
    ax_comp.set_ylabel('Y')

    if num_ranks and num_ranks > 1:
        base = nx // num_ranks
        rem = nx % num_ranks
        x_pos = 0
        for r in range(num_ranks - 1):
            loc_nx = base + (1 if r < rem else 0)
            x_pos += loc_nx
            ax_comp.axvline(x_pos, color='yellow', linestyle='--', alpha=0.9, lw=1.2)

    plt.tight_layout()

    if output_png is None:
        output_png = os.path.splitext(vtk_path)[0] + ".png"
    plt.savefig(output_png, dpi=200)
    print(f"Visualization saved to {output_png}")


def main():
    if len(sys.argv) < 2:
        print("Usage: python3 visualize_vtk.py <solution.vtk> [num_mpi_ranks]")
        sys.exit(1)

    vtk_file = sys.argv[1]
    ranks = int(sys.argv[2]) if len(sys.argv) > 2 else None
    visualize_solution(vtk_file, num_ranks=ranks)

if __name__ == "__main__":
    main()
