Phase-field Solver with Dynamic Interface Refinement: DynamicPhaseField-main/phaseFieldSolverDyTwo/phaseFieldDyTwo.C File Reference
phaseFieldDyTwo.C File Reference
#include "fvCFD.H"
#include "simpleControl.H"
#include "Random.H"
#include "dynamicFvMesh.H"
#include "setRootCase.H"
#include "createTime.H"
#include "createDynamicFvMesh.H"
#include "createFields.H"
#include "preAlan.H"
#include "alphaEqn.H"
Functions
int main (int argc, char *argv[])
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 39 of file phaseFieldDyTwo.C.
References dimx(), G(), initial(), phi(), q, and v().