Phase-field Solver with Dynamic Interface Refinement: PhaseFieldSolverDynamic/phaseFieldSolverDynamic/readTransportProperties.H File Reference
readTransportProperties.H File Reference
Functions
IOdictionary transportProperties (IOobject("transportProperties", runTime.constant(), mesh, IOobject::MUST_READ, IOobject::NO_WRITE))
The input properties to be exported to createFields.
dimensionedScalar dimt (transportProperties.lookup("dimt"))
Dimension of time.
dimensionedScalar dimx (transportProperties.lookup("dimx"))
Dimension of position.
dimensionedScalar m_1 (transportProperties.lookup("m_1"))
Slope liquidus.
dimensionedScalar m_0 (transportProperties.lookup("m_0"))
Slope solidus.
dimensionedScalar omega (transportProperties.lookup("omega"))
Relaxation coefficient for phi (order parameter)
dimensionedScalar gamma (transportProperties.lookup("gamma"))
Surface Energy.
dimensionedScalar epsilon (transportProperties.lookup("epsilon"))
Interface Width.
dimensionedScalar c_Sol (transportProperties.lookup("c_Sol"))
Composition of solid in equilibrium with liquid.
dimensionedScalar c_Liq (transportProperties.lookup("c_Liq"))
Composition of liquid in equilibrium with solid.
dimensionedScalar c_eq (transportProperties.lookup("c_eq"))
Equilibrium composition or average composition of alloy.
dimensionedScalar anti_trap (transportProperties.lookup("anti_trap"))
Anti-trapping coefficient.
dimensionedScalar diff_Sol (transportProperties.lookup("diff_Sol"))
Diffusivity in solid.
dimensionedScalar diff_Liq (transportProperties.lookup("diff_Liq"))
Diffusivity in liquid.
dimensionedScalar G (transportProperties.lookup("G"))
Thermal gradient.
dimensionedScalar v (transportProperties.lookup("v"))
Velocity.
dimensionedScalar delta_01 (transportProperties.lookup("delta_01"))
Strength of anisotropy.
dimensionedScalar A (transportProperties.lookup("A"))
dimensionedScalar B (transportProperties.lookup("B"))
dimensionedScalar T0 (transportProperties.lookup("T0"))
Melting temperature.
dimensionedScalar noise_mag (transportProperties.lookup("noise_mag"))
Noise magnitude.
dimensionedScalar initial (transportProperties.lookup("initial"))
Constant value from temperature profile.
Variables
dimensionedScalar pi = constant::mathematical::pi
The input properties are read from constant/transportProperties dictionary.
Function Documentation
transportProperties()
IOdictionary transportProperties (IOobject("transportProperties", runTime.constant(), mesh, IOobject::MUST_READ, IOobject::NO_WRITE))
The input properties to be exported to createFields.
dimt()
dimensionedScalar dimt (transportProperties. lookup"dimt")
Dimension of time.
dimx()
dimensionedScalar dimx (transportProperties. lookup"dimx")
Dimension of position.
Referenced by main().
m_1()
dimensionedScalar m_1 (transportProperties. lookup"m_1")
Slope liquidus.
m_0()
dimensionedScalar m_0 (transportProperties. lookup"m_0")
Slope solidus.
omega()
dimensionedScalar omega (transportProperties. lookup"omega")
Relaxation coefficient for phi (order parameter)
gamma()
dimensionedScalar gamma (transportProperties. lookup"gamma")
Surface Energy.
epsilon()
dimensionedScalar epsilon (transportProperties. lookup"epsilon")
Interface Width.
c_Sol()
dimensionedScalar c_Sol (transportProperties. lookup"c_Sol")
Composition of solid in equilibrium with liquid.
c_Liq()
dimensionedScalar c_Liq (transportProperties. lookup"c_Liq")
Composition of liquid in equilibrium with solid.
c_eq()
dimensionedScalar c_eq (transportProperties. lookup"c_eq")
Equilibrium composition or average composition of alloy.
anti_trap()
dimensionedScalar anti_trap (transportProperties. lookup"anti_trap")
Anti-trapping coefficient.
diff_Sol()
dimensionedScalar diff_Sol (transportProperties. lookup"diff_Sol")
Diffusivity in solid.
diff_Liq()
dimensionedScalar diff_Liq (transportProperties. lookup"diff_Liq")
Diffusivity in liquid.
G()
dimensionedScalar G (transportProperties. lookup"G")
Thermal gradient.
Referenced by main().
v()
dimensionedScalar v (transportProperties. lookup"v")
Velocity.
Referenced by main().
delta_01()
dimensionedScalar delta_01 (transportProperties. lookup"delta_01")
Strength of anisotropy.
A()
dimensionedScalar A (transportProperties. lookup"A")
B()
dimensionedScalar B (transportProperties. lookup"B")
T0()
dimensionedScalar T0 (transportProperties. lookup"T0")
Melting temperature.
noise_mag()
dimensionedScalar noise_mag (transportProperties. lookup"noise_mag")
Noise magnitude.
initial()
dimensionedScalar initial (transportProperties. lookup"initial")
Constant value from temperature profile.
Referenced by main().
Variable Documentation
pi
dimensionedScalar pi = constant::mathematical::pi
The input properties are read from constant/transportProperties dictionary.
Definition at line 15 of file readTransportProperties.H.