#!/bin/sh
g++ readInputFile.cpp -o readInputFile

./readInputFile Input_tdb_new_NiAlMo_hexagonal_orthorhomic.in Filling.in

cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

application=`getApplication`

runApplication blockMesh

cp 0/phi_1.orig 0/phi_1

cp 0/phi_2.orig 0/phi_2

cp 0/phi_3.orig 0/phi_3

cp 0/phi_4.orig 0/phi_4

cp 0/mu_1.orig 0/mu_1

cp 0/mu_2.orig 0/mu_2

cp 0/c_1.orig 0/c_1

cp 0/c_2.orig 0/c_2

cp 0/theta.orig 0/theta

cp 0/qt0.orig 0/qt0

cp 0/qt1.orig 0/qt1

cp 0/qt2.orig 0/qt2

cp 0/qt3.orig 0/qt3

cp 0/D.orig 0/D

cp 0/gradD.orig 0/gradD

cp 0/strain.orig 0/strain

cp 0/sigma.orig 0/sigma

cp 0/deltaF.orig 0/deltaF

touch phaseField.foam

#g++ -I/apps/gsl/include -c muInitial.cpp
g++ -c muInitial.cpp

#g++ -L/apps/gsl/lib muInitial.o -lgsl -lgslcblas -o muInitial
g++ muInitial.o -lgsl -lgslcblas -o muInitial

./muInitial

#rm muInitial muInitial.o

#runApplication setFields -dict system/setFieldsDict

runApplication decomposePar

#runApplication decomposePar -fileHandler collated

runParallel `getApplication`

#runApplication reconstructPar


#------------------------------------------------------------------------------
