Phase-field Solver with Dynamic Interface Refinement: PhaseFieldSolverDynamic/phaseFieldSolverDynamic/phaseFieldDynamic.C File Reference
phaseFieldDynamic.C File Reference
#include "fvCFD.H"
#include "simpleControl.H"
#include "Random.H"
#include "dynamicFvMesh.H"
#include "setRootCase.H"
#include "createTime.H"
#include "createDynamicFvMesh.H"
#include "createFields.H"
#include "preAlan.H"
#include "alphaEqn.H"
Functions
int main (int argc, char *argv[])
Using dynamicFvMesh for dynamic interface refinement.
Function Documentation
main()
int main (int argc, char * argv[])
Using dynamicFvMesh for dynamic interface refinement.
The imposed temperature field as a function of thermal gradient in the x direction, G and pulling velocity, v
The interpolation equation is used for smoothening of the phase-field variable
Solving the phase-field and chemical potential equations after updating the mesh
Writing the results according to keywords in controlDict
Definition at line 40 of file phaseFieldDynamic.C.
References dimx(), G(), initial(), phi(), q, and v().