//Do not edit this file alone. Function calls in kerenls can go wrong if any changes are made...

#pragma OPENCL EXTENSION cl_khr_fp64 : enable

void Ge(double T, double *y, double *Ge, int tpha);
void Mu(double T, double *y, double *MU, int tpha);
void dMudc(double T, double *y, double *Dmudc, int tpha
);

void Ge(double T, double *y, double *Ge, int tpha) { 

  if ( tpha == 0 ) { 
    GE_0(T, y, Ge); 
  }
  else if ( tpha == 1 ) { 
    GE_1(T, y, Ge); 
  }

}

void Mu(double T, double *y, double *MU, int tpha) { 

  if ( tpha == 0 ) { 
    Mu_0(T, y, MU); 
  }
  else if ( tpha == 1 ) { 
    Mu_1(T, y, MU); 
  }

}

void dMudc(double T, double *y, double *Dmudc, int tpha) { 

  if ( tpha == 0 ) { 
    dmudc_0(T, y, Dmudc); 
  }
  else if ( tpha == 1 ) { 
    dmudc_1(T, y, Dmudc); 
  }

}

