#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

./Allmesh

runApplication -s Domain3 decomposePar -region bufferRegion -cellProc
runApplication -s Domain1 decomposePar -region mushyRegion -cellProc
runApplication -s Domain2 decomposePar -region crucible -cellProc

runParallel $(getApplication)

#runApplication $(getApplication)

#runApplication -s Domain3 reconstructPar -region bufferRegion
#runApplication -s Domain1 reconstructPar -region mushyRegion
#runApplication -s Domain2 reconstructPar -region crucible

#------------------------------------------------------------------------------
