Phase-field Solver for Eutectic Transformation: PhaseFieldSolverEutectic/eutectic/eutectic.C File Reference
eutectic.C File Reference
#include "fvCFD.H"
#include "fvOptions.H"
#include "simpleControl.H"
#include "Random.H"
#include "setRootCase.H"
#include "createTime.H"
#include "createMesh.H"
#include "createFields.H"
#include "createTol.H"
#include "phi_abl_antiT.H"
Functions
int main (int argc, char *argv[])
Function Documentation
main()
int main (int argc, char * argv[])
The imposed temperature field as a function of thermal gradient in the x direction, G
Initial tolerance to check convergence
Solving the phase-field and chemical potential equations
Writing the results according to keywords in controlDict
Definition at line 39 of file eutectic.C.
References A(), c_eq_alpha(), c_eq_beta(), c_eq_liq(), dimx(), G(), initial(), ms_alpha(), ms_beta(), mu(), T(), and T_eut().