#!/bin/sh
#g++ initRegion.cpp -o initRegion

#./initRegion

cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

application=`getApplication`

runApplication blockMesh

#touch phaseField.foam

#g++ -I/apps/gsl/include -c muInitial.cpp
#g++ -c muInitial.cpp

#g++ -L/apps/gsl/lib muInitial.o -lgsl -lgslcblas -o muInitial
#g++ muInitial.o -lgsl -lgslcblas -o muInitial

#./muInitial

#rm muInitial muInitial.o

runApplication setFields

runApplication decomposePar

runParallel `getApplication`
#runApplication `getApplication`

#------------------------------------------------------------------------------
